In [1]:
from tensorflow.keras.models import load_model

In [2]:
import numpy as np

In [3]:
import joblib

In [4]:
nn_model = load_model("bank_churn.h5")

In [5]:
nn_model

<Sequential name=sequential, built=True>

In [6]:
sc = joblib.load('bank_scaler.pkl')

In [7]:
sc

StandardScaler()

#### Real Time Prediction

In [8]:
new_customer = [[622.0, 46.0, 4.0, 107073.27, 2.0, 1.0, 1.0, 30984.59, 0.0, 1.0, 0.0]]

In [9]:
new_customer = np.array(new_customer)

In [10]:
np.set_printoptions(precision= 2, suppress= True)

In [11]:
new_customer

array([[   622.  ,     46.  ,      4.  , 107073.27,      2.  ,      1.  ,
             1.  ,  30984.59,      0.  ,      1.  ,      0.  ]])

In [12]:
new_customer = sc.transform(new_customer)

C:\Users\sumit\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [13]:
new_customer

array([[-0.31,  0.51, -0.3 ,  0.41,  1.  ,  0.77,  1.31, -1.23, -0.57,
         2.16, -0.84]])

In [14]:
prediction = nn_model.predict(new_customer)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


In [15]:
prediction

array([[0.5]], dtype=float32)

In [16]:
prediction = prediction > 0.5

In [17]:
prediction

array([[False]])

### ********************************************************************************************************

In [18]:
def predict_churn(customer_data):
    customer_data = np.array(customer_data)
    #scaling
    customer_data = sc.transform(customer_data)
    prediction = nn_model.predict(customer_data)
    prediction = prediction > 0.5
    return prediction

In [19]:
#change the value
new_customer = [[622.0, 46.0, 4.0, 107073.27, 2.0, 1.0, 1.0, 30984.59, 0.0, 1.0, 0.0]]

In [20]:
predict_churn(new_customer)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


C:\Users\sumit\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[False]])